set(_CATKIN_CURRENT_PACKAGE "my_slam")
set(my_slam_VERSION "0.0.0")
set(my_slam_MAINTAINER "sastrygrp <sastrygrp@todo.todo>")
set(my_slam_PACKAGE_FORMAT "1")
set(my_slam_BUILD_DEPENDS "pcl_conversions" "pcl_ros" "roscpp" "rospy" "std_msgs" "sensor_msgs" "geometry_msgs" "cmake_modules" "message_generation" "libg2o" "tf")
set(my_slam_BUILD_EXPORT_DEPENDS "pcl_conversions" "pcl_ros" "roscpp" "rospy" "sensor_msgs" "std_msgs" "cmake_modules" "message_runtime" "libg2o" "tf" "cv_bridge" "libpcl-all")
set(my_slam_BUILDTOOL_DEPENDS "catkin")
set(my_slam_BUILDTOOL_EXPORT_DEPENDS )
set(my_slam_EXEC_DEPENDS "pcl_conversions" "pcl_ros" "roscpp" "rospy" "sensor_msgs" "std_msgs" "cmake_modules" "message_runtime" "libg2o" "tf" "cv_bridge" "libpcl-all")
set(my_slam_RUN_DEPENDS "pcl_conversions" "pcl_ros" "roscpp" "rospy" "sensor_msgs" "std_msgs" "cmake_modules" "message_runtime" "libg2o" "tf" "cv_bridge" "libpcl-all")
set(my_slam_TEST_DEPENDS )
set(my_slam_DOC_DEPENDS )
set(my_slam_DEPRECATED "")